// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: banked/payment/v1/errors.proto

package paymentv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _errors_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on ErrInsuffcientFunds with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ErrInsuffcientFunds) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrInsuffcientFunds with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ErrInsuffcientFundsMultiError, or nil if none found.
func (m *ErrInsuffcientFunds) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrInsuffcientFunds) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetPaymentId()); err != nil {
		err = ErrInsuffcientFundsValidationError{
			field:  "PaymentId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ErrInsuffcientFundsValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ErrInsuffcientFundsValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ErrInsuffcientFundsValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Provider

	if all {
		switch v := interface{}(m.GetAttemptedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ErrInsuffcientFundsValidationError{
					field:  "AttemptedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ErrInsuffcientFundsValidationError{
					field:  "AttemptedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAttemptedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ErrInsuffcientFundsValidationError{
				field:  "AttemptedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ErrInsuffcientFundsMultiError(errors)
	}

	return nil
}

func (m *ErrInsuffcientFunds) _validateUuid(uuid string) error {
	if matched := _errors_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ErrInsuffcientFundsMultiError is an error wrapping multiple validation
// errors returned by ErrInsuffcientFunds.ValidateAll() if the designated
// constraints aren't met.
type ErrInsuffcientFundsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrInsuffcientFundsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrInsuffcientFundsMultiError) AllErrors() []error { return m }

// ErrInsuffcientFundsValidationError is the validation error returned by
// ErrInsuffcientFunds.Validate if the designated constraints aren't met.
type ErrInsuffcientFundsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrInsuffcientFundsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrInsuffcientFundsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrInsuffcientFundsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrInsuffcientFundsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrInsuffcientFundsValidationError) ErrorName() string {
	return "ErrInsuffcientFundsValidationError"
}

// Error satisfies the builtin error interface
func (e ErrInsuffcientFundsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrInsuffcientFunds.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrInsuffcientFundsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrInsuffcientFundsValidationError{}
