// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: banked/payment/v1/service.proto

package paymentv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MakePaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MakePaymentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MakePaymentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MakePaymentRequestMultiError, or nil if none found.
func (m *MakePaymentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MakePaymentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MakePaymentRequestValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MakePaymentRequestValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MakePaymentRequestValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MakePaymentRequestMultiError(errors)
	}

	return nil
}

// MakePaymentRequestMultiError is an error wrapping multiple validation errors
// returned by MakePaymentRequest.ValidateAll() if the designated constraints
// aren't met.
type MakePaymentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MakePaymentRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MakePaymentRequestMultiError) AllErrors() []error { return m }

// MakePaymentRequestValidationError is the validation error returned by
// MakePaymentRequest.Validate if the designated constraints aren't met.
type MakePaymentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MakePaymentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MakePaymentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MakePaymentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MakePaymentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MakePaymentRequestValidationError) ErrorName() string {
	return "MakePaymentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MakePaymentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMakePaymentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MakePaymentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MakePaymentRequestValidationError{}

// Validate checks the field values on MakePaymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MakePaymentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MakePaymentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MakePaymentResponseMultiError, or nil if none found.
func (m *MakePaymentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MakePaymentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return MakePaymentResponseMultiError(errors)
	}

	return nil
}

// MakePaymentResponseMultiError is an error wrapping multiple validation
// errors returned by MakePaymentResponse.ValidateAll() if the designated
// constraints aren't met.
type MakePaymentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MakePaymentResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MakePaymentResponseMultiError) AllErrors() []error { return m }

// MakePaymentResponseValidationError is the validation error returned by
// MakePaymentResponse.Validate if the designated constraints aren't met.
type MakePaymentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MakePaymentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MakePaymentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MakePaymentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MakePaymentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MakePaymentResponseValidationError) ErrorName() string {
	return "MakePaymentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MakePaymentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMakePaymentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MakePaymentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MakePaymentResponseValidationError{}
